services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: maDataBase
        ports: [5432]